# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bipedWidget.ui'
#
# Created: Fri Nov 01 17:01:35 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_bipedWidget(object):
    def setupUi(self, bipedWidget):
        bipedWidget.setObjectName("bipedWidget")
        bipedWidget.resize(410, 775)
        self.verticalLayout = QtWidgets.QVBoxLayout(bipedWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(bipedWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.templateSettings = QtWidgets.QWidget()
        self.templateSettings.setGeometry(QtCore.QRect(0, 0, 391, 920))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateSettings.sizePolicy().hasHeightForWidth())
        self.templateSettings.setSizePolicy(sizePolicy)
        self.templateSettings.setObjectName("templateSettings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.templateSettings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.handCollapse_btn = QtWidgets.QPushButton(self.templateSettings)
        self.handCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.handCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.handCollapse_btn.setAutoFillBackground(True)
        self.handCollapse_btn.setStyleSheet("")
        self.handCollapse_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.handCollapse_btn.setIcon(icon)
        self.handCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.handCollapse_btn.setCheckable(True)
        self.handCollapse_btn.setChecked(True)
        self.handCollapse_btn.setDefault(False)
        self.handCollapse_btn.setFlat(True)
        self.handCollapse_btn.setObjectName("handCollapse_btn")
        self.horizontalLayout_2.addWidget(self.handCollapse_btn)
        self.rigName_label_2 = QtWidgets.QLabel(self.templateSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigName_label_2.sizePolicy().hasHeightForWidth())
        self.rigName_label_2.setSizePolicy(sizePolicy)
        self.rigName_label_2.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.rigName_label_2.setFont(font)
        self.rigName_label_2.setObjectName("rigName_label_2")
        self.horizontalLayout_2.addWidget(self.rigName_label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.handFrame = QtWidgets.QFrame(self.templateSettings)
        self.handFrame.setMinimumSize(QtCore.QSize(0, 191))
        self.handFrame.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.handFrame.setAutoFillBackground(False)
        self.handFrame.setStyleSheet("background rgb(203, 203, 203)")
        self.handFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.handFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.handFrame.setObjectName("handFrame")
        self.line_4 = QtWidgets.QFrame(self.handFrame)
        self.line_4.setGeometry(QtCore.QRect(0, 180, 284, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.handMiddle_spin = QtWidgets.QSpinBox(self.handFrame)
        self.handMiddle_spin.setGeometry(QtCore.QRect(90, 75, 41, 20))
        self.handMiddle_spin.setMinimum(0)
        self.handMiddle_spin.setMaximum(2)
        self.handMiddle_spin.setProperty("value", 2)
        self.handMiddle_spin.setObjectName("handMiddle_spin")
        self.handRing_chk = QtWidgets.QCheckBox(self.handFrame)
        self.handRing_chk.setGeometry(QtCore.QRect(21, 101, 45, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.handRing_chk.setFont(font)
        self.handRing_chk.setChecked(True)
        self.handRing_chk.setObjectName("handRing_chk")
        self.label_64 = QtWidgets.QLabel(self.handFrame)
        self.label_64.setGeometry(QtCore.QRect(21, 1, 22, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.handThumb_spin = QtWidgets.QSpinBox(self.handFrame)
        self.handThumb_spin.setGeometry(QtCore.QRect(90, 23, 41, 20))
        self.handThumb_spin.setMinimum(0)
        self.handThumb_spin.setMaximum(2)
        self.handThumb_spin.setProperty("value", 1)
        self.handThumb_spin.setObjectName("handThumb_spin")
        self.label_65 = QtWidgets.QLabel(self.handFrame)
        self.label_65.setGeometry(QtCore.QRect(90, 1, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.handThumb_chk = QtWidgets.QCheckBox(self.handFrame)
        self.handThumb_chk.setGeometry(QtCore.QRect(21, 23, 63, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.handThumb_chk.setFont(font)
        self.handThumb_chk.setStyleSheet("indicator:checked  {image:url(:/icon/checkbox.png); }            ")
        self.handThumb_chk.setChecked(True)
        self.handThumb_chk.setObjectName("handThumb_chk")
        self.handIndex_chk = QtWidgets.QCheckBox(self.handFrame)
        self.handIndex_chk.setGeometry(QtCore.QRect(21, 49, 53, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.handIndex_chk.setFont(font)
        self.handIndex_chk.setChecked(True)
        self.handIndex_chk.setObjectName("handIndex_chk")
        self.handIndex_spin = QtWidgets.QSpinBox(self.handFrame)
        self.handIndex_spin.setGeometry(QtCore.QRect(90, 49, 41, 20))
        self.handIndex_spin.setMinimum(0)
        self.handIndex_spin.setMaximum(2)
        self.handIndex_spin.setProperty("value", 2)
        self.handIndex_spin.setObjectName("handIndex_spin")
        self.handMiddle_chk = QtWidgets.QCheckBox(self.handFrame)
        self.handMiddle_chk.setGeometry(QtCore.QRect(21, 75, 61, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.handMiddle_chk.setFont(font)
        self.handMiddle_chk.setChecked(True)
        self.handMiddle_chk.setObjectName("handMiddle_chk")
        self.handPinky_chk = QtWidgets.QCheckBox(self.handFrame)
        self.handPinky_chk.setGeometry(QtCore.QRect(21, 127, 52, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.handPinky_chk.setFont(font)
        self.handPinky_chk.setChecked(True)
        self.handPinky_chk.setObjectName("handPinky_chk")
        self.handRing_spin = QtWidgets.QSpinBox(self.handFrame)
        self.handRing_spin.setGeometry(QtCore.QRect(90, 101, 41, 20))
        self.handRing_spin.setMinimum(0)
        self.handRing_spin.setMaximum(2)
        self.handRing_spin.setProperty("value", 2)
        self.handRing_spin.setObjectName("handRing_spin")
        self.handPinky_spin = QtWidgets.QSpinBox(self.handFrame)
        self.handPinky_spin.setGeometry(QtCore.QRect(90, 127, 41, 20))
        self.handPinky_spin.setMinimum(0)
        self.handPinky_spin.setMaximum(2)
        self.handPinky_spin.setProperty("value", 2)
        self.handPinky_spin.setObjectName("handPinky_spin")
        self.handExtra_chk = QtWidgets.QCheckBox(self.handFrame)
        self.handExtra_chk.setGeometry(QtCore.QRect(21, 153, 52, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.handExtra_chk.setFont(font)
        self.handExtra_chk.setChecked(False)
        self.handExtra_chk.setObjectName("handExtra_chk")
        self.handExtra_spin = QtWidgets.QSpinBox(self.handFrame)
        self.handExtra_spin.setGeometry(QtCore.QRect(90, 153, 41, 20))
        self.handExtra_spin.setMinimum(0)
        self.handExtra_spin.setMaximum(2)
        self.handExtra_spin.setProperty("value", 0)
        self.handExtra_spin.setObjectName("handExtra_spin")
        self.verticalLayout_4.addWidget(self.handFrame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.footCollapse_btn = QtWidgets.QPushButton(self.templateSettings)
        self.footCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.footCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.footCollapse_btn.setAutoFillBackground(True)
        self.footCollapse_btn.setStyleSheet("")
        self.footCollapse_btn.setText("")
        self.footCollapse_btn.setIcon(icon)
        self.footCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.footCollapse_btn.setCheckable(True)
        self.footCollapse_btn.setChecked(True)
        self.footCollapse_btn.setDefault(False)
        self.footCollapse_btn.setFlat(True)
        self.footCollapse_btn.setObjectName("footCollapse_btn")
        self.horizontalLayout_3.addWidget(self.footCollapse_btn)
        self.rigName_label_6 = QtWidgets.QLabel(self.templateSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigName_label_6.sizePolicy().hasHeightForWidth())
        self.rigName_label_6.setSizePolicy(sizePolicy)
        self.rigName_label_6.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.rigName_label_6.setFont(font)
        self.rigName_label_6.setAutoFillBackground(True)
        self.rigName_label_6.setObjectName("rigName_label_6")
        self.horizontalLayout_3.addWidget(self.rigName_label_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.footFrame = QtWidgets.QFrame(self.templateSettings)
        self.footFrame.setMinimumSize(QtCore.QSize(0, 191))
        self.footFrame.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.footFrame.setAutoFillBackground(False)
        self.footFrame.setStyleSheet("background rgb(203, 203, 203)")
        self.footFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.footFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footFrame.setObjectName("footFrame")
        self.line_3 = QtWidgets.QFrame(self.footFrame)
        self.line_3.setGeometry(QtCore.QRect(0, 180, 284, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_67 = QtWidgets.QLabel(self.footFrame)
        self.label_67.setGeometry(QtCore.QRect(90, 1, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.feetThumb_chk = QtWidgets.QCheckBox(self.footFrame)
        self.feetThumb_chk.setGeometry(QtCore.QRect(21, 23, 63, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.feetThumb_chk.setFont(font)
        self.feetThumb_chk.setChecked(True)
        self.feetThumb_chk.setObjectName("feetThumb_chk")
        self.label_66 = QtWidgets.QLabel(self.footFrame)
        self.label_66.setGeometry(QtCore.QRect(21, 1, 22, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.feetIndex_chk = QtWidgets.QCheckBox(self.footFrame)
        self.feetIndex_chk.setGeometry(QtCore.QRect(21, 49, 53, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.feetIndex_chk.setFont(font)
        self.feetIndex_chk.setChecked(True)
        self.feetIndex_chk.setObjectName("feetIndex_chk")
        self.feetThumb_spin = QtWidgets.QSpinBox(self.footFrame)
        self.feetThumb_spin.setGeometry(QtCore.QRect(90, 23, 41, 20))
        self.feetThumb_spin.setMinimum(0)
        self.feetThumb_spin.setMaximum(2)
        self.feetThumb_spin.setProperty("value", 1)
        self.feetThumb_spin.setObjectName("feetThumb_spin")
        self.feetIndex_spin = QtWidgets.QSpinBox(self.footFrame)
        self.feetIndex_spin.setGeometry(QtCore.QRect(90, 49, 41, 20))
        self.feetIndex_spin.setMinimum(0)
        self.feetIndex_spin.setMaximum(2)
        self.feetIndex_spin.setProperty("value", 2)
        self.feetIndex_spin.setObjectName("feetIndex_spin")
        self.feetMiddle_chk = QtWidgets.QCheckBox(self.footFrame)
        self.feetMiddle_chk.setGeometry(QtCore.QRect(21, 75, 61, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.feetMiddle_chk.setFont(font)
        self.feetMiddle_chk.setChecked(True)
        self.feetMiddle_chk.setObjectName("feetMiddle_chk")
        self.feetMiddle_spin = QtWidgets.QSpinBox(self.footFrame)
        self.feetMiddle_spin.setGeometry(QtCore.QRect(90, 75, 41, 20))
        self.feetMiddle_spin.setMinimum(0)
        self.feetMiddle_spin.setMaximum(2)
        self.feetMiddle_spin.setProperty("value", 2)
        self.feetMiddle_spin.setObjectName("feetMiddle_spin")
        self.feetRing_chk = QtWidgets.QCheckBox(self.footFrame)
        self.feetRing_chk.setGeometry(QtCore.QRect(21, 101, 45, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.feetRing_chk.setFont(font)
        self.feetRing_chk.setChecked(True)
        self.feetRing_chk.setObjectName("feetRing_chk")
        self.feetRing_spin = QtWidgets.QSpinBox(self.footFrame)
        self.feetRing_spin.setGeometry(QtCore.QRect(90, 101, 41, 20))
        self.feetRing_spin.setMinimum(0)
        self.feetRing_spin.setMaximum(2)
        self.feetRing_spin.setProperty("value", 2)
        self.feetRing_spin.setObjectName("feetRing_spin")
        self.feetPinky_chk = QtWidgets.QCheckBox(self.footFrame)
        self.feetPinky_chk.setGeometry(QtCore.QRect(22, 127, 52, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.feetPinky_chk.setFont(font)
        self.feetPinky_chk.setChecked(True)
        self.feetPinky_chk.setObjectName("feetPinky_chk")
        self.feetPinky_spin = QtWidgets.QSpinBox(self.footFrame)
        self.feetPinky_spin.setGeometry(QtCore.QRect(91, 127, 41, 20))
        self.feetPinky_spin.setMinimum(1)
        self.feetPinky_spin.setMaximum(3)
        self.feetPinky_spin.setProperty("value", 2)
        self.feetPinky_spin.setObjectName("feetPinky_spin")
        self.feetExtra_chk = QtWidgets.QCheckBox(self.footFrame)
        self.feetExtra_chk.setGeometry(QtCore.QRect(22, 153, 52, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.feetExtra_chk.setFont(font)
        self.feetExtra_chk.setObjectName("feetExtra_chk")
        self.feetExtra_spin = QtWidgets.QSpinBox(self.footFrame)
        self.feetExtra_spin.setGeometry(QtCore.QRect(91, 153, 41, 20))
        self.feetExtra_spin.setMinimum(1)
        self.feetExtra_spin.setMaximum(3)
        self.feetExtra_spin.setObjectName("feetExtra_spin")
        self.verticalLayout_4.addWidget(self.footFrame)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.armRibbonCollapse_btn = QtWidgets.QPushButton(self.templateSettings)
        self.armRibbonCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.armRibbonCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.armRibbonCollapse_btn.setAutoFillBackground(False)
        self.armRibbonCollapse_btn.setStyleSheet("")
        self.armRibbonCollapse_btn.setText("")
        self.armRibbonCollapse_btn.setIcon(icon)
        self.armRibbonCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.armRibbonCollapse_btn.setCheckable(True)
        self.armRibbonCollapse_btn.setChecked(True)
        self.armRibbonCollapse_btn.setDefault(False)
        self.armRibbonCollapse_btn.setFlat(True)
        self.armRibbonCollapse_btn.setObjectName("armRibbonCollapse_btn")
        self.horizontalLayout_4.addWidget(self.armRibbonCollapse_btn)
        self.rigName_label_7 = QtWidgets.QLabel(self.templateSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigName_label_7.sizePolicy().hasHeightForWidth())
        self.rigName_label_7.setSizePolicy(sizePolicy)
        self.rigName_label_7.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.rigName_label_7.setFont(font)
        self.rigName_label_7.setObjectName("rigName_label_7")
        self.horizontalLayout_4.addWidget(self.rigName_label_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.armRibbon_frame = QtWidgets.QFrame(self.templateSettings)
        self.armRibbon_frame.setMinimumSize(QtCore.QSize(0, 121))
        self.armRibbon_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.armRibbon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.armRibbon_frame.setObjectName("armRibbon_frame")
        self.line_2 = QtWidgets.QFrame(self.armRibbon_frame)
        self.line_2.setGeometry(QtCore.QRect(0, 110, 291, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.armLastOffset_label = QtWidgets.QLabel(self.armRibbon_frame)
        self.armLastOffset_label.setGeometry(QtCore.QRect(70, 82, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.armLastOffset_label.sizePolicy().hasHeightForWidth())
        self.armLastOffset_label.setSizePolicy(sizePolicy)
        self.armLastOffset_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.armLastOffset_label.setFont(font)
        self.armLastOffset_label.setObjectName("armLastOffset_label")
        self.armFirstOffset_label = QtWidgets.QLabel(self.armRibbon_frame)
        self.armFirstOffset_label.setGeometry(QtCore.QRect(70, 56, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.armFirstOffset_label.sizePolicy().hasHeightForWidth())
        self.armFirstOffset_label.setSizePolicy(sizePolicy)
        self.armFirstOffset_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.armFirstOffset_label.setFont(font)
        self.armFirstOffset_label.setObjectName("armFirstOffset_label")
        self.armFirstOffset_spin = QtWidgets.QSpinBox(self.armRibbon_frame)
        self.armFirstOffset_spin.setGeometry(QtCore.QRect(22, 53, 41, 20))
        self.armFirstOffset_spin.setProperty("value", 1)
        self.armFirstOffset_spin.setObjectName("armFirstOffset_spin")
        self.armNumJnts_label = QtWidgets.QLabel(self.armRibbon_frame)
        self.armNumJnts_label.setGeometry(QtCore.QRect(70, 30, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.armNumJnts_label.sizePolicy().hasHeightForWidth())
        self.armNumJnts_label.setSizePolicy(sizePolicy)
        self.armNumJnts_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.armNumJnts_label.setFont(font)
        self.armNumJnts_label.setObjectName("armNumJnts_label")
        self.armNumJnts_spin = QtWidgets.QSpinBox(self.armRibbon_frame)
        self.armNumJnts_spin.setGeometry(QtCore.QRect(22, 27, 41, 20))
        self.armNumJnts_spin.setProperty("value", 5)
        self.armNumJnts_spin.setObjectName("armNumJnts_spin")
        self.armRibbon_chk = QtWidgets.QCheckBox(self.armRibbon_frame)
        self.armRibbon_chk.setGeometry(QtCore.QRect(22, 1, 62, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.armRibbon_chk.setFont(font)
        self.armRibbon_chk.setChecked(True)
        self.armRibbon_chk.setObjectName("armRibbon_chk")
        self.armLastOffset_spin = QtWidgets.QSpinBox(self.armRibbon_frame)
        self.armLastOffset_spin.setGeometry(QtCore.QRect(22, 79, 41, 20))
        self.armLastOffset_spin.setProperty("value", 1)
        self.armLastOffset_spin.setObjectName("armLastOffset_spin")
        self.verticalLayout_4.addWidget(self.armRibbon_frame)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.legRibbonCollapse_btn = QtWidgets.QPushButton(self.templateSettings)
        self.legRibbonCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.legRibbonCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.legRibbonCollapse_btn.setAutoFillBackground(True)
        self.legRibbonCollapse_btn.setText("")
        self.legRibbonCollapse_btn.setIcon(icon)
        self.legRibbonCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.legRibbonCollapse_btn.setCheckable(True)
        self.legRibbonCollapse_btn.setChecked(True)
        self.legRibbonCollapse_btn.setDefault(False)
        self.legRibbonCollapse_btn.setFlat(True)
        self.legRibbonCollapse_btn.setObjectName("legRibbonCollapse_btn")
        self.horizontalLayout_5.addWidget(self.legRibbonCollapse_btn)
        self.rigName_label_8 = QtWidgets.QLabel(self.templateSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigName_label_8.sizePolicy().hasHeightForWidth())
        self.rigName_label_8.setSizePolicy(sizePolicy)
        self.rigName_label_8.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.rigName_label_8.setFont(font)
        self.rigName_label_8.setObjectName("rigName_label_8")
        self.horizontalLayout_5.addWidget(self.rigName_label_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.legRibbon_frame = QtWidgets.QFrame(self.templateSettings)
        self.legRibbon_frame.setMinimumSize(QtCore.QSize(0, 121))
        self.legRibbon_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.legRibbon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.legRibbon_frame.setObjectName("legRibbon_frame")
        self.line = QtWidgets.QFrame(self.legRibbon_frame)
        self.line.setGeometry(QtCore.QRect(10, 110, 261, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.legRibbon_chk = QtWidgets.QCheckBox(self.legRibbon_frame)
        self.legRibbon_chk.setGeometry(QtCore.QRect(22, 1, 62, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.legRibbon_chk.setFont(font)
        self.legRibbon_chk.setChecked(True)
        self.legRibbon_chk.setObjectName("legRibbon_chk")
        self.legNumJnts_spin = QtWidgets.QSpinBox(self.legRibbon_frame)
        self.legNumJnts_spin.setGeometry(QtCore.QRect(22, 27, 41, 20))
        self.legNumJnts_spin.setSingleStep(1)
        self.legNumJnts_spin.setProperty("value", 5)
        self.legNumJnts_spin.setObjectName("legNumJnts_spin")
        self.legLastOffset_label = QtWidgets.QLabel(self.legRibbon_frame)
        self.legLastOffset_label.setGeometry(QtCore.QRect(70, 82, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legLastOffset_label.sizePolicy().hasHeightForWidth())
        self.legLastOffset_label.setSizePolicy(sizePolicy)
        self.legLastOffset_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.legLastOffset_label.setFont(font)
        self.legLastOffset_label.setObjectName("legLastOffset_label")
        self.legFirstOffset_spin = QtWidgets.QSpinBox(self.legRibbon_frame)
        self.legFirstOffset_spin.setGeometry(QtCore.QRect(22, 53, 41, 20))
        self.legFirstOffset_spin.setProperty("value", 1)
        self.legFirstOffset_spin.setObjectName("legFirstOffset_spin")
        self.legNumJnts_label = QtWidgets.QLabel(self.legRibbon_frame)
        self.legNumJnts_label.setGeometry(QtCore.QRect(70, 30, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legNumJnts_label.sizePolicy().hasHeightForWidth())
        self.legNumJnts_label.setSizePolicy(sizePolicy)
        self.legNumJnts_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.legNumJnts_label.setFont(font)
        self.legNumJnts_label.setObjectName("legNumJnts_label")
        self.legLastOffset_spin = QtWidgets.QSpinBox(self.legRibbon_frame)
        self.legLastOffset_spin.setGeometry(QtCore.QRect(22, 79, 41, 20))
        self.legLastOffset_spin.setProperty("value", 1)
        self.legLastOffset_spin.setObjectName("legLastOffset_spin")
        self.legFirstOffset_label = QtWidgets.QLabel(self.legRibbon_frame)
        self.legFirstOffset_label.setGeometry(QtCore.QRect(70, 56, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legFirstOffset_label.sizePolicy().hasHeightForWidth())
        self.legFirstOffset_label.setSizePolicy(sizePolicy)
        self.legFirstOffset_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.legFirstOffset_label.setFont(font)
        self.legFirstOffset_label.setObjectName("legFirstOffset_label")
        self.verticalLayout_4.addWidget(self.legRibbon_frame)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spineCollapse_btn = QtWidgets.QPushButton(self.templateSettings)
        self.spineCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.spineCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spineCollapse_btn.setAutoFillBackground(False)
        self.spineCollapse_btn.setStyleSheet("")
        self.spineCollapse_btn.setText("")
        self.spineCollapse_btn.setIcon(icon)
        self.spineCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.spineCollapse_btn.setCheckable(True)
        self.spineCollapse_btn.setChecked(True)
        self.spineCollapse_btn.setDefault(False)
        self.spineCollapse_btn.setFlat(True)
        self.spineCollapse_btn.setObjectName("spineCollapse_btn")
        self.horizontalLayout_6.addWidget(self.spineCollapse_btn)
        self.rigName_label_3 = QtWidgets.QLabel(self.templateSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigName_label_3.sizePolicy().hasHeightForWidth())
        self.rigName_label_3.setSizePolicy(sizePolicy)
        self.rigName_label_3.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.rigName_label_3.setFont(font)
        self.rigName_label_3.setObjectName("rigName_label_3")
        self.horizontalLayout_6.addWidget(self.rigName_label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.spineRibbon_frame = QtWidgets.QFrame(self.templateSettings)
        self.spineRibbon_frame.setMinimumSize(QtCore.QSize(0, 91))
        self.spineRibbon_frame.setMaximumSize(QtCore.QSize(16777215, 91))
        self.spineRibbon_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spineRibbon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spineRibbon_frame.setObjectName("spineRibbon_frame")
        self.legFistOffset_label = QtWidgets.QLabel(self.spineRibbon_frame)
        self.legFistOffset_label.setGeometry(QtCore.QRect(70, 34, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legFistOffset_label.sizePolicy().hasHeightForWidth())
        self.legFistOffset_label.setSizePolicy(sizePolicy)
        self.legFistOffset_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.legFistOffset_label.setFont(font)
        self.legFistOffset_label.setObjectName("legFistOffset_label")
        self.spineNumJnts_spin = QtWidgets.QSpinBox(self.spineRibbon_frame)
        self.spineNumJnts_spin.setGeometry(QtCore.QRect(22, 1, 41, 20))
        self.spineNumJnts_spin.setProperty("value", 5)
        self.spineNumJnts_spin.setObjectName("spineNumJnts_spin")
        self.spineFistOffset_spin = QtWidgets.QSpinBox(self.spineRibbon_frame)
        self.spineFistOffset_spin.setGeometry(QtCore.QRect(22, 27, 41, 20))
        self.spineFistOffset_spin.setProperty("value", 1)
        self.spineFistOffset_spin.setObjectName("spineFistOffset_spin")
        self.spineNumJnts_label = QtWidgets.QLabel(self.spineRibbon_frame)
        self.spineNumJnts_label.setGeometry(QtCore.QRect(70, 8, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spineNumJnts_label.sizePolicy().hasHeightForWidth())
        self.spineNumJnts_label.setSizePolicy(sizePolicy)
        self.spineNumJnts_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.spineNumJnts_label.setFont(font)
        self.spineNumJnts_label.setObjectName("spineNumJnts_label")
        self.spineLastOffset_spin = QtWidgets.QSpinBox(self.spineRibbon_frame)
        self.spineLastOffset_spin.setGeometry(QtCore.QRect(22, 53, 41, 20))
        self.spineLastOffset_spin.setProperty("value", 1)
        self.spineLastOffset_spin.setObjectName("spineLastOffset_spin")
        self.spineLastOffset_label = QtWidgets.QLabel(self.spineRibbon_frame)
        self.spineLastOffset_label.setGeometry(QtCore.QRect(70, 60, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spineLastOffset_label.sizePolicy().hasHeightForWidth())
        self.spineLastOffset_label.setSizePolicy(sizePolicy)
        self.spineLastOffset_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.spineLastOffset_label.setFont(font)
        self.spineLastOffset_label.setObjectName("spineLastOffset_label")
        self.verticalLayout_4.addWidget(self.spineRibbon_frame)
        spacerItem = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea.setWidget(self.templateSettings)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(bipedWidget)
        QtCore.QObject.connect(self.handCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.handFrame.setVisible)
        QtCore.QObject.connect(self.footCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.footFrame.setVisible)
        QtCore.QObject.connect(self.armRibbonCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.armRibbon_frame.setVisible)
        QtCore.QObject.connect(self.legRibbonCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.legRibbon_frame.setVisible)
        QtCore.QObject.connect(self.spineCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.spineRibbon_frame.setVisible)
        QtCore.QMetaObject.connectSlotsByName(bipedWidget)

    def retranslateUi(self, bipedWidget):
        bipedWidget.setWindowTitle(QtWidgets.QApplication.translate("bipedWidget", "Form", None, -1))
        self.rigName_label_2.setText(QtWidgets.QApplication.translate("bipedWidget", "Hand Fingers", None, -1))
        self.handRing_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "ring", None, -1))
        self.label_64.setText(QtWidgets.QApplication.translate("bipedWidget", "Toe", None, -1))
        self.label_65.setText(QtWidgets.QApplication.translate("bipedWidget", "Phalanx", None, -1))
        self.handThumb_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "Thumb", None, -1))
        self.handIndex_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "index", None, -1))
        self.handMiddle_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "middle", None, -1))
        self.handPinky_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "pinky", None, -1))
        self.handExtra_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "extra", None, -1))
        self.rigName_label_6.setText(QtWidgets.QApplication.translate("bipedWidget", "Foot Fingers", None, -1))
        self.label_67.setText(QtWidgets.QApplication.translate("bipedWidget", "Phalanx", None, -1))
        self.feetThumb_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "Thumb", None, -1))
        self.label_66.setText(QtWidgets.QApplication.translate("bipedWidget", "Toe", None, -1))
        self.feetIndex_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "index", None, -1))
        self.feetMiddle_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "middle", None, -1))
        self.feetRing_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "ring", None, -1))
        self.feetPinky_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "pinky", None, -1))
        self.feetExtra_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "extra", None, -1))
        self.rigName_label_7.setText(QtWidgets.QApplication.translate("bipedWidget", "Arm Ribbon", None, -1))
        self.armLastOffset_label.setText(QtWidgets.QApplication.translate("bipedWidget", "Last Joint Offset", None, -1))
        self.armFirstOffset_label.setText(QtWidgets.QApplication.translate("bipedWidget", "First Joint Offset", None, -1))
        self.armNumJnts_label.setText(QtWidgets.QApplication.translate("bipedWidget", "Number of Joints", None, -1))
        self.armRibbon_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "Ribbon", None, -1))
        self.rigName_label_8.setText(QtWidgets.QApplication.translate("bipedWidget", "Leg Ribbon", None, -1))
        self.legRibbon_chk.setText(QtWidgets.QApplication.translate("bipedWidget", "Ribbon", None, -1))
        self.legLastOffset_label.setText(QtWidgets.QApplication.translate("bipedWidget", "First Joint Offset", None, -1))
        self.legNumJnts_label.setText(QtWidgets.QApplication.translate("bipedWidget", "Number of Joints", None, -1))
        self.legFirstOffset_label.setText(QtWidgets.QApplication.translate("bipedWidget", "First Joint Offset", None, -1))
        self.rigName_label_3.setText(QtWidgets.QApplication.translate("bipedWidget", "Spine Ribbon", None, -1))
        self.legFistOffset_label.setText(QtWidgets.QApplication.translate("bipedWidget", "First Joint Offset", None, -1))
        self.spineNumJnts_label.setText(QtWidgets.QApplication.translate("bipedWidget", "Number of Joints", None, -1))
        self.spineLastOffset_label.setText(QtWidgets.QApplication.translate("bipedWidget", "Last Joint Offset", None, -1))

import icons_rc
