# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bodyRigWidget.ui'
#
# Created: Fri Apr  3 13:12:30 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_autoRig(object):
    def setupUi(self, autoRig):
        autoRig.setObjectName("autoRig")
        autoRig.resize(277, 1013)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(autoRig.sizePolicy().hasHeightForWidth())
        autoRig.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(autoRig)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(autoRig)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.menu_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn.sizePolicy().hasHeightForWidth())
        self.menu_btn.setSizePolicy(sizePolicy)
        self.menu_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/bars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon)
        self.menu_btn.setIconSize(QtCore.QSize(16, 16))
        self.menu_btn.setFlat(True)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_7.addWidget(self.menu_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rigName_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigName_label.sizePolicy().hasHeightForWidth())
        self.rigName_label.setSizePolicy(sizePolicy)
        self.rigName_label.setMinimumSize(QtCore.QSize(0, 25))
        self.rigName_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rigName_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.rigName_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.rigName_label.setFont(font)
        self.rigName_label.setObjectName("rigName_label")
        self.horizontalLayout_8.addWidget(self.rigName_label)
        self.rigName_txt = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigName_txt.sizePolicy().hasHeightForWidth())
        self.rigName_txt.setSizePolicy(sizePolicy)
        self.rigName_txt.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.rigName_txt.setFont(font)
        self.rigName_txt.setObjectName("rigName_txt")
        self.horizontalLayout_8.addWidget(self.rigName_txt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.widget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 90))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 90))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connect_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_label.sizePolicy().hasHeightForWidth())
        self.connect_label.setSizePolicy(sizePolicy)
        self.connect_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.connect_label.setFont(font)
        self.connect_label.setObjectName("connect_label")
        self.horizontalLayout.addWidget(self.connect_label)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hierarchy_rdBtn = QtWidgets.QRadioButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.hierarchy_rdBtn.setFont(font)
        self.hierarchy_rdBtn.setChecked(True)
        self.hierarchy_rdBtn.setObjectName("hierarchy_rdBtn")
        self.verticalLayout_2.addWidget(self.hierarchy_rdBtn)
        self.constraint_rdBtn = QtWidgets.QRadioButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.constraint_rdBtn.setFont(font)
        self.constraint_rdBtn.setObjectName("constraint_rdBtn")
        self.verticalLayout_2.addWidget(self.constraint_rdBtn)
        self.horizontalLayout.addWidget(self.widget_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.widget)
        self.template_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.template_label.sizePolicy().hasHeightForWidth())
        self.template_label.setSizePolicy(sizePolicy)
        self.template_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.template_label.setFont(font)
        self.template_label.setObjectName("template_label")
        self.verticalLayout_4.addWidget(self.template_label)
        self.template_comboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.template_comboBox.sizePolicy().hasHeightForWidth())
        self.template_comboBox.setSizePolicy(sizePolicy)
        self.template_comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.template_comboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.template_comboBox.setFont(font)
        self.template_comboBox.setObjectName("template_comboBox")
        self.template_comboBox.addItem("")
        self.template_comboBox.addItem("")
        self.template_comboBox.addItem("")
        self.template_comboBox.addItem("")
        self.template_comboBox.addItem("")
        self.template_comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.template_comboBox)
        self.template_placeHolder = QtWidgets.QVBoxLayout()
        self.template_placeHolder.setSpacing(0)
        self.template_placeHolder.setObjectName("template_placeHolder")
        self.verticalLayout_4.addLayout(self.template_placeHolder)
        self.getGuide_chk = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.getGuide_chk.setFont(font)
        self.getGuide_chk.setObjectName("getGuide_chk")
        self.verticalLayout_4.addWidget(self.getGuide_chk)
        self.createGuide_btn = QtWidgets.QPushButton(self.frame)
        self.createGuide_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.createGuide_btn.setFont(font)
        self.createGuide_btn.setObjectName("createGuide_btn")
        self.verticalLayout_4.addWidget(self.createGuide_btn)
        self.reapplySkin_chk = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.reapplySkin_chk.setFont(font)
        self.reapplySkin_chk.setObjectName("reapplySkin_chk")
        self.verticalLayout_4.addWidget(self.reapplySkin_chk)
        self.createRig_btn = QtWidgets.QPushButton(self.frame)
        self.createRig_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.createRig_btn.setFont(font)
        self.createRig_btn.setObjectName("createRig_btn")
        self.verticalLayout_4.addWidget(self.createRig_btn)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(autoRig)
        QtCore.QMetaObject.connectSlotsByName(autoRig)

    def retranslateUi(self, autoRig):
        autoRig.setWindowTitle(QtWidgets.QApplication.translate("autoRig", "AUTORIG", None, -1))
        self.rigName_label.setText(QtWidgets.QApplication.translate("autoRig", " Name ", None, -1))
        self.rigName_txt.setText(QtWidgets.QApplication.translate("autoRig", "character", None, -1))
        self.connect_label.setText(QtWidgets.QApplication.translate("autoRig", "Modules Connection", None, -1))
        self.hierarchy_rdBtn.setText(QtWidgets.QApplication.translate("autoRig", "Hierarchy", None, -1))
        self.constraint_rdBtn.setText(QtWidgets.QApplication.translate("autoRig", "Constraints", None, -1))
        self.template_label.setText(QtWidgets.QApplication.translate("autoRig", "Template", None, -1))
        self.template_comboBox.setItemText(0, QtWidgets.QApplication.translate("autoRig", "Biped", None, -1))
        self.template_comboBox.setItemText(1, QtWidgets.QApplication.translate("autoRig", "Quadruped", None, -1))
        self.template_comboBox.setItemText(2, QtWidgets.QApplication.translate("autoRig", "Bird", None, -1))
        self.template_comboBox.setItemText(3, QtWidgets.QApplication.translate("autoRig", "BipedNoSpine", None, -1))
        self.template_comboBox.setItemText(4, QtWidgets.QApplication.translate("autoRig", "BipedLongNeck", None, -1))
        self.template_comboBox.setItemText(5, QtWidgets.QApplication.translate("autoRig", "QuadrupedLongNeck", None, -1))
        self.getGuide_chk.setText(QtWidgets.QApplication.translate("autoRig", "Get guide position from scene", None, -1))
        self.createGuide_btn.setText(QtWidgets.QApplication.translate("autoRig", "CREATE GUIDES", None, -1))
        self.reapplySkin_chk.setText(QtWidgets.QApplication.translate("autoRig", "Reaply Skin when rebuildng rig", None, -1))
        self.createRig_btn.setText(QtWidgets.QApplication.translate("autoRig", "CREATE RIG", None, -1))

import icons_rc
