# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlsWidget.ui'
#
# Created: Sat Jan 25 20:35:59 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(303, 881)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(240, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.controlShapesCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.controlShapesCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.controlShapesCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.controlShapesCollapse_btn.setAutoFillBackground(True)
        self.controlShapesCollapse_btn.setStyleSheet("")
        self.controlShapesCollapse_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.controlShapesCollapse_btn.setIcon(icon)
        self.controlShapesCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.controlShapesCollapse_btn.setCheckable(True)
        self.controlShapesCollapse_btn.setChecked(True)
        self.controlShapesCollapse_btn.setDefault(False)
        self.controlShapesCollapse_btn.setFlat(True)
        self.controlShapesCollapse_btn.setObjectName("controlShapesCollapse_btn")
        self.horizontalLayout_15.addWidget(self.controlShapesCollapse_btn)
        self.lookat_label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label_2.sizePolicy().hasHeightForWidth())
        self.lookat_label_2.setSizePolicy(sizePolicy)
        self.lookat_label_2.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label_2.setFont(font)
        self.lookat_label_2.setObjectName("lookat_label_2")
        self.horizontalLayout_15.addWidget(self.lookat_label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.controlShape_frame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlShape_frame.sizePolicy().hasHeightForWidth())
        self.controlShape_frame.setSizePolicy(sizePolicy)
        self.controlShape_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.controlShape_frame.setObjectName("controlShape_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.controlShape_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addToLayers_chk = QtWidgets.QCheckBox(self.controlShape_frame)
        self.addToLayers_chk.setEnabled(False)
        self.addToLayers_chk.setMinimumSize(QtCore.QSize(0, 20))
        self.addToLayers_chk.setChecked(True)
        self.addToLayers_chk.setObjectName("addToLayers_chk")
        self.verticalLayout_2.addWidget(self.addToLayers_chk)
        self.autoColor_chk = QtWidgets.QCheckBox(self.controlShape_frame)
        self.autoColor_chk.setMinimumSize(QtCore.QSize(0, 20))
        self.autoColor_chk.setChecked(True)
        self.autoColor_chk.setObjectName("autoColor_chk")
        self.verticalLayout_2.addWidget(self.autoColor_chk)
        self.parentSelectOrder_chk = QtWidgets.QCheckBox(self.controlShape_frame)
        self.parentSelectOrder_chk.setMinimumSize(QtCore.QSize(0, 20))
        self.parentSelectOrder_chk.setChecked(True)
        self.parentSelectOrder_chk.setObjectName("parentSelectOrder_chk")
        self.verticalLayout_2.addWidget(self.parentSelectOrder_chk)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.offsetGroups_chk = QtWidgets.QCheckBox(self.controlShape_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetGroups_chk.sizePolicy().hasHeightForWidth())
        self.offsetGroups_chk.setSizePolicy(sizePolicy)
        self.offsetGroups_chk.setAutoFillBackground(False)
        self.offsetGroups_chk.setChecked(False)
        self.offsetGroups_chk.setObjectName("offsetGroups_chk")
        self.horizontalLayout.addWidget(self.offsetGroups_chk)
        self.offsetsNumber_spin = QtWidgets.QSpinBox(self.controlShape_frame)
        self.offsetsNumber_spin.setProperty("value", 1)
        self.offsetsNumber_spin.setObjectName("offsetsNumber_spin")
        self.horizontalLayout.addWidget(self.offsetsNumber_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.controlShape_frame)
        self.label.setMinimumSize(QtCore.QSize(115, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.globalScale_spin = QtWidgets.QDoubleSpinBox(self.controlShape_frame)
        self.globalScale_spin.setProperty("value", 1.0)
        self.globalScale_spin.setObjectName("globalScale_spin")
        self.horizontalLayout_2.addWidget(self.globalScale_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.connectionType_comboBox = QtWidgets.QComboBox(self.controlShape_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.connectionType_comboBox.setFont(font)
        self.connectionType_comboBox.setObjectName("connectionType_comboBox")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.connectionType_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.connectionType_comboBox)
        self.scrollArea = QtWidgets.QScrollArea(self.controlShape_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.shapeButtons_widget = QtWidgets.QWidget()
        self.shapeButtons_widget.setGeometry(QtCore.QRect(0, 0, 266, 540))
        self.shapeButtons_widget.setObjectName("shapeButtons_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.shapeButtons_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolButton_49 = QtWidgets.QToolButton(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_49.sizePolicy().hasHeightForWidth())
        self.toolButton_49.setSizePolicy(sizePolicy)
        self.toolButton_49.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_49.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.toolButton_49.setFont(font)
        self.toolButton_49.setWhatsThis("jaw")
        self.toolButton_49.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolButton_49.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/controls/icon/red/jaw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_49.setIcon(icon1)
        self.toolButton_49.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_49.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_49.setObjectName("toolButton_49")
        self.gridLayout_2.addWidget(self.toolButton_49, 9, 0, 1, 1)
        self.pushButton_42 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_42.sizePolicy().hasHeightForWidth())
        self.pushButton_42.setSizePolicy(sizePolicy)
        self.pushButton_42.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_42.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setWhatsThis("drop_X")
        self.pushButton_42.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/controls/icon/red/drop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_42.setIcon(icon2)
        self.pushButton_42.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_42.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_2.addWidget(self.pushButton_42, 8, 0, 1, 1)
        self.toolButton_40 = QtWidgets.QToolButton(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_40.sizePolicy().hasHeightForWidth())
        self.toolButton_40.setSizePolicy(sizePolicy)
        self.toolButton_40.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_40.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.toolButton_40.setFont(font)
        self.toolButton_40.setWhatsThis("bank")
        self.toolButton_40.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolButton_40.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/controls/icon/red/bank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_40.setIcon(icon3)
        self.toolButton_40.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_40.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_40.setAutoRaise(False)
        self.toolButton_40.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_40.setObjectName("toolButton_40")
        self.gridLayout_2.addWidget(self.toolButton_40, 6, 1, 1, 1)
        self.pushButton_39 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_39.sizePolicy().hasHeightForWidth())
        self.pushButton_39.setSizePolicy(sizePolicy)
        self.pushButton_39.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_39.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setWhatsThis("cog_X")
        self.pushButton_39.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/controls/icon/red/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_39.setIcon(icon4)
        self.pushButton_39.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_39.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_2.addWidget(self.pushButton_39, 6, 0, 1, 1)
        self.pushButton_45 = QtWidgets.QToolButton(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_45.sizePolicy().hasHeightForWidth())
        self.pushButton_45.setSizePolicy(sizePolicy)
        self.pushButton_45.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_45.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setWhatsThis("guideDir_X")
        self.pushButton_45.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_45.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/controls/icon/red/guideDir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_45.setIcon(icon5)
        self.pushButton_45.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_45.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_2.addWidget(self.pushButton_45, 17, 0, 1, 1)
        self.toolButton_41 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_41.sizePolicy().hasHeightForWidth())
        self.toolButton_41.setSizePolicy(sizePolicy)
        self.toolButton_41.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_41.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.toolButton_41.setFont(font)
        self.toolButton_41.setWhatsThis("fkControl_x")
        self.toolButton_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/controls/icon/red/fkControl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_41.setIcon(icon6)
        self.toolButton_41.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_41.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_41.setObjectName("toolButton_41")
        self.gridLayout_2.addWidget(self.toolButton_41, 2, 2, 1, 1)
        self.pushButton_50 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_50.sizePolicy().hasHeightForWidth())
        self.pushButton_50.setSizePolicy(sizePolicy)
        self.pushButton_50.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_50.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setWhatsThis("ponteiroReto_X")
        self.pushButton_50.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/controls/icon/red/ponteiroReto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_50.setIcon(icon7)
        self.pushButton_50.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_50.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout_2.addWidget(self.pushButton_50, 8, 1, 1, 1)
        self.pushButton_46 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_46.sizePolicy().hasHeightForWidth())
        self.pushButton_46.setSizePolicy(sizePolicy)
        self.pushButton_46.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_46.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setWhatsThis("gota_X")
        self.pushButton_46.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/controls/icon/red/gota.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_46.setIcon(icon8)
        self.pushButton_46.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_46.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_2.addWidget(self.pushButton_46, 9, 2, 1, 1)
        self.pushButton_56 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_56.sizePolicy().hasHeightForWidth())
        self.pushButton_56.setSizePolicy(sizePolicy)
        self.pushButton_56.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_56.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setWhatsThis("circulo_X")
        self.pushButton_56.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/controls/icon/red/circulo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_56.setIcon(icon9)
        self.pushButton_56.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_56.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout_2.addWidget(self.pushButton_56, 1, 0, 1, 1)
        self.pushButton_44 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_44.sizePolicy().hasHeightForWidth())
        self.pushButton_44.setSizePolicy(sizePolicy)
        self.pushButton_44.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_44.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setWhatsThis("hexagono_X")
        self.pushButton_44.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/controls/icon/red/hexagono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_44.setIcon(icon10)
        self.pushButton_44.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_44.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_2.addWidget(self.pushButton_44, 3, 0, 1, 1)
        self.pushButton_61 = QtWidgets.QToolButton(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_61.sizePolicy().hasHeightForWidth())
        self.pushButton_61.setSizePolicy(sizePolicy)
        self.pushButton_61.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_61.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setWhatsThis("bola")
        self.pushButton_61.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_61.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/controls/icon/blue/bola.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_61.setIcon(icon11)
        self.pushButton_61.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_61.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_61.setObjectName("pushButton_61")
        self.gridLayout_2.addWidget(self.pushButton_61, 2, 1, 1, 1)
        self.pushButton_37 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_37.sizePolicy().hasHeightForWidth())
        self.pushButton_37.setSizePolicy(sizePolicy)
        self.pushButton_37.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_37.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setWhatsThis("triangulo_X")
        self.pushButton_37.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/controls/icon/red/triangulo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_37.setIcon(icon12)
        self.pushButton_37.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_37.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_2.addWidget(self.pushButton_37, 1, 2, 1, 1)
        self.pushButton_36 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_36.sizePolicy().hasHeightForWidth())
        self.pushButton_36.setSizePolicy(sizePolicy)
        self.pushButton_36.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_36.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setWhatsThis("quadrado_Z")
        self.pushButton_36.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/controls/icon/red/quadrado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_36.setIcon(icon13)
        self.pushButton_36.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_36.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.pushButton_36.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_2.addWidget(self.pushButton_36, 1, 1, 1, 1)
        self.toolButton_43 = QtWidgets.QToolButton(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_43.sizePolicy().hasHeightForWidth())
        self.toolButton_43.setSizePolicy(sizePolicy)
        self.toolButton_43.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_43.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.toolButton_43.setFont(font)
        self.toolButton_43.setWhatsThis("cubo")
        self.toolButton_43.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolButton_43.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/controls/icon/red/cubo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_43.setIcon(icon14)
        self.toolButton_43.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_43.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_43.setObjectName("toolButton_43")
        self.gridLayout_2.addWidget(self.toolButton_43, 2, 0, 1, 1)
        self.pushButton_52 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_52.sizePolicy().hasHeightForWidth())
        self.pushButton_52.setSizePolicy(sizePolicy)
        self.pushButton_52.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_52.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setWhatsThis("pentagono_X")
        self.pushButton_52.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/controls/icon/red/pentagono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_52.setIcon(icon15)
        self.pushButton_52.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_52.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout_2.addWidget(self.pushButton_52, 3, 1, 1, 1)
        self.pushButton_55 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_55.sizePolicy().hasHeightForWidth())
        self.pushButton_55.setSizePolicy(sizePolicy)
        self.pushButton_55.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_55.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setWhatsThis("retangulo_X")
        self.pushButton_55.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/controls/icon/red/retangulo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_55.setIcon(icon16)
        self.pushButton_55.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_55.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout_2.addWidget(self.pushButton_55, 3, 2, 1, 1)
        self.pushButton_51 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_51.sizePolicy().hasHeightForWidth())
        self.pushButton_51.setSizePolicy(sizePolicy)
        self.pushButton_51.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_51.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setWhatsThis("ponteiro_X")
        self.pushButton_51.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/controls/icon/red/ponteiro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_51.setIcon(icon17)
        self.pushButton_51.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_51.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout_2.addWidget(self.pushButton_51, 8, 2, 1, 1)
        self.toolButton_47 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_47.sizePolicy().hasHeightForWidth())
        self.toolButton_47.setSizePolicy(sizePolicy)
        self.toolButton_47.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_47.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.toolButton_47.setFont(font)
        self.toolButton_47.setWhatsThis("lowerTeeth")
        self.toolButton_47.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/controls/icon/red/lowerTeeth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_47.setIcon(icon18)
        self.toolButton_47.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_47.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_47.setObjectName("toolButton_47")
        self.gridLayout_2.addWidget(self.toolButton_47, 17, 1, 1, 1)
        self.pushButton_53 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_53.sizePolicy().hasHeightForWidth())
        self.pushButton_53.setSizePolicy(sizePolicy)
        self.pushButton_53.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_53.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setWhatsThis("circulo_X")
        self.pushButton_53.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/controls/icon/red/seta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_53.setIcon(icon19)
        self.pushButton_53.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_53.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout_2.addWidget(self.pushButton_53, 4, 0, 1, 1)
        self.pushButton_48 = QtWidgets.QToolButton(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_48.sizePolicy().hasHeightForWidth())
        self.pushButton_48.setSizePolicy(sizePolicy)
        self.pushButton_48.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_48.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setWhatsThis("lamp")
        self.pushButton_48.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_48.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/controls/icon/red/lamp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_48.setIcon(icon20)
        self.pushButton_48.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_48.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_2.addWidget(self.pushButton_48, 17, 2, 1, 1)
        self.pushButton_54 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_54.sizePolicy().hasHeightForWidth())
        self.pushButton_54.setSizePolicy(sizePolicy)
        self.pushButton_54.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_54.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setWhatsThis("semiCirculo_X")
        self.pushButton_54.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/controls/icon/red/semiCirculo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_54.setIcon(icon21)
        self.pushButton_54.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_54.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout_2.addWidget(self.pushButton_54, 4, 2, 1, 1)
        self.pushButton_38 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_38.sizePolicy().hasHeightForWidth())
        self.pushButton_38.setSizePolicy(sizePolicy)
        self.pushButton_38.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_38.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setWhatsThis("cross_X")
        self.pushButton_38.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/controls/icon/red/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_38.setIcon(icon22)
        self.pushButton_38.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_38.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_2.addWidget(self.pushButton_38, 4, 1, 1, 1)
        self.pushButton_58 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_58.sizePolicy().hasHeightForWidth())
        self.pushButton_58.setSizePolicy(sizePolicy)
        self.pushButton_58.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_58.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setWhatsThis("circulo_X")
        self.pushButton_58.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_58.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_58.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout_2.addWidget(self.pushButton_58, 9, 1, 1, 1)
        self.pushButton_35 = IconButtonContextMenu(self.shapeButtons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_35.sizePolicy().hasHeightForWidth())
        self.pushButton_35.setSizePolicy(sizePolicy)
        self.pushButton_35.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_35.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setWhatsThis("circuloPonta_X")
        self.pushButton_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_35.setText("X")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/controls/icon/blue/circuloPonta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_35.setIcon(icon23)
        self.pushButton_35.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_35.setShortcut("")
        self.pushButton_35.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_2.addWidget(self.pushButton_35, 6, 2, 1, 1)
        self.scrollArea.setWidget(self.shapeButtons_widget)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.pushButton_5 = QtWidgets.QPushButton(self.controlShape_frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout_3.addWidget(self.controlShape_frame)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.colorsCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.colorsCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.colorsCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.colorsCollapse_btn.setAutoFillBackground(True)
        self.colorsCollapse_btn.setStyleSheet("")
        self.colorsCollapse_btn.setText("")
        self.colorsCollapse_btn.setIcon(icon)
        self.colorsCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.colorsCollapse_btn.setCheckable(True)
        self.colorsCollapse_btn.setChecked(True)
        self.colorsCollapse_btn.setDefault(False)
        self.colorsCollapse_btn.setFlat(True)
        self.colorsCollapse_btn.setObjectName("colorsCollapse_btn")
        self.horizontalLayout_16.addWidget(self.colorsCollapse_btn)
        self.lookat_label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label_3.sizePolicy().hasHeightForWidth())
        self.lookat_label_3.setSizePolicy(sizePolicy)
        self.lookat_label_3.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label_3.setFont(font)
        self.lookat_label_3.setObjectName("lookat_label_3")
        self.horizontalLayout_16.addWidget(self.lookat_label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.colors_frame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colors_frame.sizePolicy().hasHeightForWidth())
        self.colors_frame.setSizePolicy(sizePolicy)
        self.colors_frame.setMinimumSize(QtCore.QSize(210, 104))
        self.colors_frame.setMaximumSize(QtCore.QSize(160000, 104))
        self.colors_frame.setObjectName("colors_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.colors_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_19 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_19.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_19.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_19.setStyleSheet("background:rgb(255.000000, 255.000000, 255.000000)")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 0, 0, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_28.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_28.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_28.setStyleSheet("background:rgb(47.940000, 159.885000, 93.075000)")
        self.pushButton_28.setText("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_28, 0, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_12.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_12.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_12.setStyleSheet("background:rgb(0.000000, 70.125000, 23.970000)")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 0, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_11.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_11.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_11.setStyleSheet("background:rgb(0.000000, 4.080000, 95.115000)")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_4.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_4.setStyleSheet("background:rgb(36.975000, 0.000000, 67.065000)")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 4, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_18.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_18.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_18.setStyleSheet("background:rgb(61.965000, 33.915000, 31.110000)")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 0, 5, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_15.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_15.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_15.setStyleSheet("background:rgb(136.935000, 70.890000, 51.000000)")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 0, 6, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton.setStyleSheet("background:rgb(0.0, 0, 0)")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 7, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_26.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_26.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_26.setStyleSheet("background:rgb(158.100000, 159.885000, 47.940000)")
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 1, 0, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_27.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_27.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_27.setStyleSheet("background:rgb(104.040000, 159.885000, 47.940000)")
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_27, 1, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_24.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_24.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_24.setStyleSheet("background:rgb(0.000000, 153.000000, 82.875000)")
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_9.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_9.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_9.setStyleSheet("background:rgb(0.000000, 65.025000, 153.000000)")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 3, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_31.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_31.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_31.setStyleSheet("background:rgb(110.925000, 47.940000, 159.885000)")
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_31, 1, 4, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_57.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_57.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_57.setStyleSheet("background:rgb(153.000000, 36.975000, 0.000000)")
        self.pushButton_57.setText("")
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout.addWidget(self.pushButton_57, 1, 5, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_25.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_25.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_25.setStyleSheet("background:rgb(159.885000, 105.060000, 47.940000)")
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 1, 6, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_13.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_13.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_13.setStyleSheet("background:rgb(63, 63, 63)")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 7, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_23.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_23.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_23.setAccessibleName("")
        self.pushButton_23.setStyleSheet("background:rgb(255.000000, 255.000000, 97.920000)")
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 2, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_20.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_20.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_20.setStyleSheet("background:rgb(67.065000, 255.000000, 161.925000)")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 2, 1, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_29.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_29.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_29.setStyleSheet("background:rgb(47.940000, 159.885000, 159.885000)")
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_29, 2, 2, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_30.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_30.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_30.setStyleSheet("background:rgb(47.940000, 103.020000, 159.885000)")
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_30, 2, 3, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_32.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_32.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_32.setAccessibleName("")
        self.pushButton_32.setStyleSheet("background:rgb(159.885000, 47.940000, 105.060000)")
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_32, 2, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_3.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_3.setStyleSheet("background:rgb(155.04, 0, 40.035000000000004)")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 5, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_22.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_22.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_22.setStyleSheet("background:rgb(226.950000, 172.125000, 121.125000)")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 2, 6, 1, 1)
        self.pushButton_59 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_59.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_59.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_59.setStyleSheet("background:rgb(126, 126, 126)")
        self.pushButton_59.setText("")
        self.pushButton_59.setObjectName("pushButton_59")
        self.gridLayout.addWidget(self.pushButton_59, 2, 7, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_10.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_10.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_10.setStyleSheet("background:rgb(255.000000, 255.000000, 0.000000)")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_60 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_60.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_60.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_60.setAccessibleDescription("")
        self.pushButton_60.setStyleSheet("background:rgb(0.000000, 255.000000, 0.000000)")
        self.pushButton_60.setText("")
        self.pushButton_60.setObjectName("pushButton_60")
        self.gridLayout.addWidget(self.pushButton_60, 3, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_17.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_17.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_17.setStyleSheet("background:rgb(98.940000, 220.065000, 255.000000)")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 3, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_14.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_14.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_14.setAccessibleName("")
        self.pushButton_14.setStyleSheet("background:rgb(0.000000, 0.000000, 255.000000)")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 3, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_16.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_16.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_16.setStyleSheet("background:rgb(198.900000, 0.000000, 198.900000)")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 4, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_8.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_8.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_8.setAccessibleName("")
        self.pushButton_8.setStyleSheet("background:rgb(255.000000, 0.000000, 0.000000)")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 5, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_21.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_21.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_21.setStyleSheet("background:rgb(255.000000, 174.930000, 174.930000)")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 3, 6, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.colors_frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_2.setMaximumSize(QtCore.QSize(26, 26))
        self.pushButton_2.setStyleSheet("background:rgb(202, 202, 202)")
        self.pushButton_2.setText("")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 7, 1, 1)
        self.verticalLayout_3.addWidget(self.colors_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.controlShapesCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.controlShape_frame.setVisible)
        QtCore.QObject.connect(self.colorsCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.colors_frame.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.lookat_label_2.setText(QtWidgets.QApplication.translate("Form", "CONTROL SHAPES", None, -1))
        self.addToLayers_chk.setText(QtWidgets.QApplication.translate("Form", "add to layers", None, -1))
        self.autoColor_chk.setText(QtWidgets.QApplication.translate("Form", "auto color by prefix", None, -1))
        self.parentSelectOrder_chk.setText(QtWidgets.QApplication.translate("Form", "parent by selection order", None, -1))
        self.offsetGroups_chk.setText(QtWidgets.QApplication.translate("Form", "create offsetGroups", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "global size", None, -1))
        self.connectionType_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "parentScaleConstraint", None, -1))
        self.connectionType_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "parentConstraint", None, -1))
        self.connectionType_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "orientConstraint", None, -1))
        self.connectionType_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "orientScaleConstraint", None, -1))
        self.connectionType_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "pointConstraint", None, -1))
        self.connectionType_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "pointScaleConstraint", None, -1))
        self.connectionType_comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "connectionTRS", None, -1))
        self.connectionType_comboBox.setItemText(7, QtWidgets.QApplication.translate("Form", "connectionTR", None, -1))
        self.connectionType_comboBox.setItemText(8, QtWidgets.QApplication.translate("Form", "connectionTS", None, -1))
        self.connectionType_comboBox.setItemText(9, QtWidgets.QApplication.translate("Form", "connectionRS", None, -1))
        self.connectionType_comboBox.setItemText(10, QtWidgets.QApplication.translate("Form", "connectionT", None, -1))
        self.connectionType_comboBox.setItemText(11, QtWidgets.QApplication.translate("Form", "connectionR", None, -1))
        self.connectionType_comboBox.setItemText(12, QtWidgets.QApplication.translate("Form", "connectionS", None, -1))
        self.connectionType_comboBox.setItemText(13, QtWidgets.QApplication.translate("Form", "change Shape", None, -1))
        self.pushButton_42.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_39.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.toolButton_41.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_50.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_46.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_56.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_44.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_37.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_36.setText(QtWidgets.QApplication.translate("Form", "Z", None, -1))
        self.pushButton_52.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_55.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_51.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.toolButton_47.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_53.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_54.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_38.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_58.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("Form", "FLIP SEL SHAPE", None, -1))
        self.lookat_label_3.setText(QtWidgets.QApplication.translate("Form", "COLORS", None, -1))
        self.pushButton_19.setWhatsThis(QtWidgets.QApplication.translate("Form", "16", None, -1))
        self.pushButton_28.setWhatsThis(QtWidgets.QApplication.translate("Form", "27", None, -1))
        self.pushButton_12.setWhatsThis(QtWidgets.QApplication.translate("Form", "7", None, -1))
        self.pushButton_11.setWhatsThis(QtWidgets.QApplication.translate("Form", "5", None, -1))
        self.pushButton_4.setWhatsThis(QtWidgets.QApplication.translate("Form", "8", None, -1))
        self.pushButton_18.setWhatsThis(QtWidgets.QApplication.translate("Form", "11", None, -1))
        self.pushButton_15.setWhatsThis(QtWidgets.QApplication.translate("Form", "10", None, -1))
        self.pushButton.setWhatsThis(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.pushButton_26.setWhatsThis(QtWidgets.QApplication.translate("Form", "25", None, -1))
        self.pushButton_27.setWhatsThis(QtWidgets.QApplication.translate("Form", "26", None, -1))
        self.pushButton_24.setWhatsThis(QtWidgets.QApplication.translate("Form", "23", None, -1))
        self.pushButton_9.setWhatsThis(QtWidgets.QApplication.translate("Form", "15", None, -1))
        self.pushButton_31.setWhatsThis(QtWidgets.QApplication.translate("Form", "30", None, -1))
        self.pushButton_57.setWhatsThis(QtWidgets.QApplication.translate("Form", "12", None, -1))
        self.pushButton_25.setWhatsThis(QtWidgets.QApplication.translate("Form", "24", None, -1))
        self.pushButton_13.setWhatsThis(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.pushButton_23.setWhatsThis(QtWidgets.QApplication.translate("Form", "22", None, -1))
        self.pushButton_20.setWhatsThis(QtWidgets.QApplication.translate("Form", "19", None, -1))
        self.pushButton_29.setWhatsThis(QtWidgets.QApplication.translate("Form", "28", None, -1))
        self.pushButton_30.setWhatsThis(QtWidgets.QApplication.translate("Form", "29", None, -1))
        self.pushButton_32.setWhatsThis(QtWidgets.QApplication.translate("Form", "31", None, -1))
        self.pushButton_3.setWhatsThis(QtWidgets.QApplication.translate("Form", "4", None, -1))
        self.pushButton_22.setWhatsThis(QtWidgets.QApplication.translate("Form", "21", None, -1))
        self.pushButton_59.setWhatsThis(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.pushButton_10.setWhatsThis(QtWidgets.QApplication.translate("Form", "17", None, -1))
        self.pushButton_60.setWhatsThis(QtWidgets.QApplication.translate("Form", "14", None, -1))
        self.pushButton_17.setWhatsThis(QtWidgets.QApplication.translate("Form", "18", None, -1))
        self.pushButton_14.setWhatsThis(QtWidgets.QApplication.translate("Form", "6", None, -1))
        self.pushButton_16.setWhatsThis(QtWidgets.QApplication.translate("Form", "9", None, -1))
        self.pushButton_8.setWhatsThis(QtWidgets.QApplication.translate("Form", "13", None, -1))
        self.pushButton_21.setWhatsThis(QtWidgets.QApplication.translate("Form", "20", None, -1))
        self.pushButton_2.setWhatsThis(QtWidgets.QApplication.translate("Form", "0", None, -1))

from autoRig3.ui.customWidgets.iconButtonContextMenu import IconButtonContextMenu
import icons_rc
