# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skinWidget.ui'
#
# Created: Sat Jan 25 20:35:17 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 745)
        Form.setMinimumSize(QtCore.QSize(240, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ngCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.ngCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.ngCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ngCollapse_btn.setAutoFillBackground(True)
        self.ngCollapse_btn.setStyleSheet("")
        self.ngCollapse_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ngCollapse_btn.setIcon(icon)
        self.ngCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.ngCollapse_btn.setCheckable(True)
        self.ngCollapse_btn.setChecked(True)
        self.ngCollapse_btn.setDefault(False)
        self.ngCollapse_btn.setFlat(True)
        self.ngCollapse_btn.setObjectName("ngCollapse_btn")
        self.horizontalLayout_16.addWidget(self.ngCollapse_btn)
        self.lookat_label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label_3.sizePolicy().hasHeightForWidth())
        self.lookat_label_3.setSizePolicy(sizePolicy)
        self.lookat_label_3.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label_3.setFont(font)
        self.lookat_label_3.setObjectName("lookat_label_3")
        self.horizontalLayout_16.addWidget(self.lookat_label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.ng_frame = QtWidgets.QFrame(self.frame)
        self.ng_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ng_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ng_frame.setObjectName("ng_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ng_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_30 = QtWidgets.QLabel(self.ng_frame)
        self.label_30.setMinimumSize(QtCore.QSize(55, 0))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout.addWidget(self.label_30)
        self.ng_iteractions_spin = QtWidgets.QSpinBox(self.ng_frame)
        self.ng_iteractions_spin.setMinimumSize(QtCore.QSize(53, 0))
        self.ng_iteractions_spin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ng_iteractions_spin.setProperty("value", 30)
        self.ng_iteractions_spin.setObjectName("ng_iteractions_spin")
        self.horizontalLayout.addWidget(self.ng_iteractions_spin)
        self.ng_iteractions_slider = QtWidgets.QSlider(self.ng_frame)
        self.ng_iteractions_slider.setMinimumSize(QtCore.QSize(0, 20))
        self.ng_iteractions_slider.setProperty("value", 30)
        self.ng_iteractions_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ng_iteractions_slider.setObjectName("ng_iteractions_slider")
        self.horizontalLayout.addWidget(self.ng_iteractions_slider)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_31 = QtWidgets.QLabel(self.ng_frame)
        self.label_31.setMinimumSize(QtCore.QSize(55, 0))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.label_31)
        self.ng_stepSize_spin = QtWidgets.QDoubleSpinBox(self.ng_frame)
        self.ng_stepSize_spin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ng_stepSize_spin.setProperty("value", 0.15)
        self.ng_stepSize_spin.setObjectName("ng_stepSize_spin")
        self.horizontalLayout_2.addWidget(self.ng_stepSize_spin)
        self.ng_stepSize_slider = QtWidgets.QSlider(self.ng_frame)
        self.ng_stepSize_slider.setMinimumSize(QtCore.QSize(0, 20))
        self.ng_stepSize_slider.setProperty("value", 15)
        self.ng_stepSize_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ng_stepSize_slider.setObjectName("ng_stepSize_slider")
        self.horizontalLayout_2.addWidget(self.ng_stepSize_slider)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.ng_mayaNativeSelection_chk = QtWidgets.QCheckBox(self.ng_frame)
        self.ng_mayaNativeSelection_chk.setChecked(True)
        self.ng_mayaNativeSelection_chk.setObjectName("ng_mayaNativeSelection_chk")
        self.verticalLayout_5.addWidget(self.ng_mayaNativeSelection_chk)
        self.ng_relax_btn = QtWidgets.QPushButton(self.ng_frame)
        self.ng_relax_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.ng_relax_btn.setObjectName("ng_relax_btn")
        self.verticalLayout_5.addWidget(self.ng_relax_btn)
        self.verticalLayout_2.addWidget(self.ng_frame)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setMinimumSize(QtCore.QSize(0, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.saveSkinCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.saveSkinCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.saveSkinCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveSkinCollapse_btn.setAutoFillBackground(True)
        self.saveSkinCollapse_btn.setStyleSheet("")
        self.saveSkinCollapse_btn.setText("")
        self.saveSkinCollapse_btn.setIcon(icon)
        self.saveSkinCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.saveSkinCollapse_btn.setCheckable(True)
        self.saveSkinCollapse_btn.setChecked(True)
        self.saveSkinCollapse_btn.setDefault(False)
        self.saveSkinCollapse_btn.setFlat(True)
        self.saveSkinCollapse_btn.setObjectName("saveSkinCollapse_btn")
        self.horizontalLayout_17.addWidget(self.saveSkinCollapse_btn)
        self.lookat_label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label_4.sizePolicy().hasHeightForWidth())
        self.lookat_label_4.setSizePolicy(sizePolicy)
        self.lookat_label_4.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label_4.setFont(font)
        self.lookat_label_4.setObjectName("lookat_label_4")
        self.horizontalLayout_17.addWidget(self.lookat_label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.saveSkin_frame = QtWidgets.QFrame(self.frame)
        self.saveSkin_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveSkin_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveSkin_frame.setObjectName("saveSkin_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.saveSkin_frame)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.skinName_txt = QtWidgets.QLineEdit(self.saveSkin_frame)
        self.skinName_txt.setObjectName("skinName_txt")
        self.horizontalLayout_4.addWidget(self.skinName_txt)
        self.skinBrowse_btn = QtWidgets.QPushButton(self.saveSkin_frame)
        self.skinBrowse_btn.setObjectName("skinBrowse_btn")
        self.horizontalLayout_4.addWidget(self.skinBrowse_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveSkin_btn = QtWidgets.QPushButton(self.saveSkin_frame)
        self.saveSkin_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.saveSkin_btn.setObjectName("saveSkin_btn")
        self.horizontalLayout_3.addWidget(self.saveSkin_btn)
        self.loadSkin_btn = QtWidgets.QPushButton(self.saveSkin_frame)
        self.loadSkin_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.loadSkin_btn.setObjectName("loadSkin_btn")
        self.horizontalLayout_3.addWidget(self.loadSkin_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.saveSkin_frame)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.skinToolsCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.skinToolsCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.skinToolsCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skinToolsCollapse_btn.setAutoFillBackground(True)
        self.skinToolsCollapse_btn.setStyleSheet("")
        self.skinToolsCollapse_btn.setText("")
        self.skinToolsCollapse_btn.setIcon(icon)
        self.skinToolsCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.skinToolsCollapse_btn.setCheckable(True)
        self.skinToolsCollapse_btn.setChecked(True)
        self.skinToolsCollapse_btn.setDefault(False)
        self.skinToolsCollapse_btn.setFlat(True)
        self.skinToolsCollapse_btn.setObjectName("skinToolsCollapse_btn")
        self.horizontalLayout_14.addWidget(self.skinToolsCollapse_btn)
        self.lookat_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label.sizePolicy().hasHeightForWidth())
        self.lookat_label.setSizePolicy(sizePolicy)
        self.lookat_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label.setFont(font)
        self.lookat_label.setObjectName("lookat_label")
        self.horizontalLayout_14.addWidget(self.lookat_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.skinTools_frame = QtWidgets.QFrame(self.frame)
        self.skinTools_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.skinTools_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.skinTools_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.skinTools_frame.setObjectName("skinTools_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.skinTools_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.transferSkin_btn = QtWidgets.QToolButton(self.skinTools_frame)
        self.transferSkin_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.transferSkin_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.transferSkin_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/skin/icon/transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transferSkin_btn.setIcon(icon1)
        self.transferSkin_btn.setIconSize(QtCore.QSize(50, 50))
        self.transferSkin_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.transferSkin_btn.setObjectName("transferSkin_btn")
        self.gridLayout.addWidget(self.transferSkin_btn, 0, 0, 1, 1)
        self.copyVtx_btn = QtWidgets.QToolButton(self.skinTools_frame)
        self.copyVtx_btn.setEnabled(False)
        self.copyVtx_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.copyVtx_btn.setMaximumSize(QtCore.QSize(75, 75))
        self.copyVtx_btn.setObjectName("copyVtx_btn")
        self.gridLayout.addWidget(self.copyVtx_btn, 0, 1, 1, 1)
        self.mirrorSkin_btn = QtWidgets.QToolButton(self.skinTools_frame)
        self.mirrorSkin_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.mirrorSkin_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.mirrorSkin_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/skin/icon/mirror.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mirrorSkin_btn.setIcon(icon2)
        self.mirrorSkin_btn.setIconSize(QtCore.QSize(50, 50))
        self.mirrorSkin_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mirrorSkin_btn.setObjectName("mirrorSkin_btn")
        self.gridLayout.addWidget(self.mirrorSkin_btn, 1, 0, 1, 1)
        self.pasteVtx_btn = QtWidgets.QToolButton(self.skinTools_frame)
        self.pasteVtx_btn.setEnabled(False)
        self.pasteVtx_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.pasteVtx_btn.setMaximumSize(QtCore.QSize(75, 75))
        self.pasteVtx_btn.setObjectName("pasteVtx_btn")
        self.gridLayout.addWidget(self.pasteVtx_btn, 1, 1, 1, 1)
        self.copySkin_btn = QtWidgets.QToolButton(self.skinTools_frame)
        self.copySkin_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.copySkin_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.copySkin_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/skin/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copySkin_btn.setIcon(icon3)
        self.copySkin_btn.setIconSize(QtCore.QSize(40, 40))
        self.copySkin_btn.setShortcut("")
        self.copySkin_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.copySkin_btn.setObjectName("copySkin_btn")
        self.gridLayout.addWidget(self.copySkin_btn, 2, 0, 1, 1)
        self.edgeSkin_btn = QtWidgets.QToolButton(self.skinTools_frame)
        self.edgeSkin_btn.setEnabled(False)
        self.edgeSkin_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.edgeSkin_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.edgeSkin_btn.setFont(font)
        self.edgeSkin_btn.setIcon(icon1)
        self.edgeSkin_btn.setIconSize(QtCore.QSize(40, 40))
        self.edgeSkin_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.edgeSkin_btn.setObjectName("edgeSkin_btn")
        self.gridLayout.addWidget(self.edgeSkin_btn, 2, 1, 1, 1)
        self.resetSkin_btn = QtWidgets.QToolButton(self.skinTools_frame)
        self.resetSkin_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.resetSkin_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.resetSkin_btn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/skin/icon/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetSkin_btn.setIcon(icon4)
        self.resetSkin_btn.setIconSize(QtCore.QSize(50, 50))
        self.resetSkin_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.resetSkin_btn.setObjectName("resetSkin_btn")
        self.gridLayout.addWidget(self.resetSkin_btn, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.skinTools_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.ng_iteractions_slider, QtCore.SIGNAL("sliderMoved(int)"), self.ng_iteractions_spin.setValue)
        QtCore.QObject.connect(self.ng_iteractions_spin, QtCore.SIGNAL("valueChanged(int)"), self.ng_iteractions_slider.setValue)
        QtCore.QObject.connect(self.ngCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.ng_frame.setVisible)
        QtCore.QObject.connect(self.saveSkinCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.saveSkin_frame.setVisible)
        QtCore.QObject.connect(self.skinToolsCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.skinTools_frame.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.lookat_label_3.setText(QtWidgets.QApplication.translate("Form", "NG SKIN RELAX", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("Form", "Iteractions", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("Form", "step size", None, -1))
        self.ng_mayaNativeSelection_chk.setText(QtWidgets.QApplication.translate("Form", "Use Maya Soft Selection", None, -1))
        self.ng_relax_btn.setText(QtWidgets.QApplication.translate("Form", "SMOOTH SKIN", None, -1))
        self.lookat_label_4.setText(QtWidgets.QApplication.translate("Form", "SAVE SKIN", None, -1))
        self.skinBrowse_btn.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.saveSkin_btn.setText(QtWidgets.QApplication.translate("Form", "SAVE SKIN", None, -1))
        self.loadSkin_btn.setText(QtWidgets.QApplication.translate("Form", "LOAD SKIN", None, -1))
        self.lookat_label.setText(QtWidgets.QApplication.translate("Form", "SKIN TOOLS", None, -1))
        self.transferSkin_btn.setText(QtWidgets.QApplication.translate("Form", "TRANSFER", None, -1))
        self.copyVtx_btn.setText(QtWidgets.QApplication.translate("Form", "COPY VTX", None, -1))
        self.mirrorSkin_btn.setText(QtWidgets.QApplication.translate("Form", "MIRROR", None, -1))
        self.pasteVtx_btn.setText(QtWidgets.QApplication.translate("Form", "PASTE VTX", None, -1))
        self.copySkin_btn.setText(QtWidgets.QApplication.translate("Form", "COPY", None, -1))
        self.edgeSkin_btn.setText(QtWidgets.QApplication.translate("Form", "EDGE SKIN", None, -1))
        self.resetSkin_btn.setText(QtWidgets.QApplication.translate("Form", "RESET", None, -1))

import icons_rc
