# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sourcesWidget.ui'
#
# Created: Sat Jan 25 20:35:00 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 648)
        Form.setMinimumSize(QtCore.QSize(240, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.sourceCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.sourceCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.sourceCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sourceCollapse_btn.setAutoFillBackground(True)
        self.sourceCollapse_btn.setStyleSheet("")
        self.sourceCollapse_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.sourceCollapse_btn.setIcon(icon)
        self.sourceCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.sourceCollapse_btn.setCheckable(True)
        self.sourceCollapse_btn.setChecked(True)
        self.sourceCollapse_btn.setDefault(False)
        self.sourceCollapse_btn.setFlat(True)
        self.sourceCollapse_btn.setObjectName("sourceCollapse_btn")
        self.horizontalLayout_15.addWidget(self.sourceCollapse_btn)
        self.lookat_label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label_2.sizePolicy().hasHeightForWidth())
        self.lookat_label_2.setSizePolicy(sizePolicy)
        self.lookat_label_2.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label_2.setFont(font)
        self.lookat_label_2.setObjectName("lookat_label_2")
        self.horizontalLayout_15.addWidget(self.lookat_label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.source_frame = QtWidgets.QFrame(self.frame)
        self.source_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.source_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.source_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.source_frame.setObjectName("source_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.source_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sources_refresh_btn = QtWidgets.QPushButton(self.source_frame)
        self.sources_refresh_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sources_refresh_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sources_refresh_btn.setObjectName("sources_refresh_btn")
        self.verticalLayout_2.addWidget(self.sources_refresh_btn)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sources_append_btn = QtWidgets.QPushButton(self.source_frame)
        self.sources_append_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.sources_append_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sources_append_btn.setObjectName("sources_append_btn")
        self.horizontalLayout_5.addWidget(self.sources_append_btn)
        self.sources_remove_btn = QtWidgets.QPushButton(self.source_frame)
        self.sources_remove_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sources_remove_btn.setObjectName("sources_remove_btn")
        self.horizontalLayout_5.addWidget(self.sources_remove_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.sources_listWidget = QtWidgets.QListWidget(self.source_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sources_listWidget.sizePolicy().hasHeightForWidth())
        self.sources_listWidget.setSizePolicy(sizePolicy)
        self.sources_listWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.sources_listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sources_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sources_listWidget.setObjectName("sources_listWidget")
        self.verticalLayout_2.addWidget(self.sources_listWidget)
        self.sources_addToSource_btn = QtWidgets.QPushButton(self.source_frame)
        self.sources_addToSource_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.sources_addToSource_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sources_addToSource_btn.setObjectName("sources_addToSource_btn")
        self.verticalLayout_2.addWidget(self.sources_addToSource_btn)
        self.connectSources_btn = QtWidgets.QPushButton(self.source_frame)
        self.connectSources_btn.setEnabled(False)
        self.connectSources_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.connectSources_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.connectSources_btn.setObjectName("connectSources_btn")
        self.verticalLayout_2.addWidget(self.connectSources_btn)
        self.verticalLayout_3.addWidget(self.source_frame)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.meshToolsCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.meshToolsCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.meshToolsCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.meshToolsCollapse_btn.setAutoFillBackground(True)
        self.meshToolsCollapse_btn.setStyleSheet("")
        self.meshToolsCollapse_btn.setText("")
        self.meshToolsCollapse_btn.setIcon(icon)
        self.meshToolsCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.meshToolsCollapse_btn.setCheckable(True)
        self.meshToolsCollapse_btn.setChecked(True)
        self.meshToolsCollapse_btn.setDefault(False)
        self.meshToolsCollapse_btn.setFlat(True)
        self.meshToolsCollapse_btn.setObjectName("meshToolsCollapse_btn")
        self.horizontalLayout_16.addWidget(self.meshToolsCollapse_btn)
        self.lookat_label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label_3.sizePolicy().hasHeightForWidth())
        self.lookat_label_3.setSizePolicy(sizePolicy)
        self.lookat_label_3.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label_3.setFont(font)
        self.lookat_label_3.setObjectName("lookat_label_3")
        self.horizontalLayout_16.addWidget(self.lookat_label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.meshTool_frame = QtWidgets.QFrame(self.frame)
        self.meshTool_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.meshTool_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.meshTool_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.meshTool_frame.setObjectName("meshTool_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.meshTool_frame)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mesh_transferUV_btn = QtWidgets.QToolButton(self.meshTool_frame)
        self.mesh_transferUV_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.mesh_transferUV_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.mesh_transferUV_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sources/icon/transferUV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mesh_transferUV_btn.setIcon(icon1)
        self.mesh_transferUV_btn.setIconSize(QtCore.QSize(50, 50))
        self.mesh_transferUV_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mesh_transferUV_btn.setObjectName("mesh_transferUV_btn")
        self.gridLayout.addWidget(self.mesh_transferUV_btn, 1, 0, 1, 1)
        self.mesh_cleaner_btn = QtWidgets.QToolButton(self.meshTool_frame)
        self.mesh_cleaner_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.mesh_cleaner_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.mesh_cleaner_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sources/icon/clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mesh_cleaner_btn.setIcon(icon2)
        self.mesh_cleaner_btn.setIconSize(QtCore.QSize(40, 40))
        self.mesh_cleaner_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mesh_cleaner_btn.setObjectName("mesh_cleaner_btn")
        self.gridLayout.addWidget(self.mesh_cleaner_btn, 0, 0, 1, 1)
        self.mesh_changeGeo_btn = QtWidgets.QToolButton(self.meshTool_frame)
        self.mesh_changeGeo_btn.setEnabled(False)
        self.mesh_changeGeo_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.mesh_changeGeo_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.mesh_changeGeo_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/skin/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mesh_changeGeo_btn.setIcon(icon3)
        self.mesh_changeGeo_btn.setIconSize(QtCore.QSize(40, 40))
        self.mesh_changeGeo_btn.setShortcut("")
        self.mesh_changeGeo_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mesh_changeGeo_btn.setObjectName("mesh_changeGeo_btn")
        self.gridLayout.addWidget(self.mesh_changeGeo_btn, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.saveSkin_frame_2 = QtWidgets.QFrame(self.meshTool_frame)
        self.saveSkin_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveSkin_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveSkin_frame_2.setObjectName("saveSkin_frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.saveSkin_frame_2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mesh_uvName_txt = QtWidgets.QLineEdit(self.saveSkin_frame_2)
        self.mesh_uvName_txt.setEnabled(False)
        self.mesh_uvName_txt.setObjectName("mesh_uvName_txt")
        self.horizontalLayout_6.addWidget(self.mesh_uvName_txt)
        self.mesh_browseUV_btn = QtWidgets.QPushButton(self.saveSkin_frame_2)
        self.mesh_browseUV_btn.setEnabled(False)
        self.mesh_browseUV_btn.setObjectName("mesh_browseUV_btn")
        self.horizontalLayout_6.addWidget(self.mesh_browseUV_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mesh_saveUV_btn = QtWidgets.QPushButton(self.saveSkin_frame_2)
        self.mesh_saveUV_btn.setEnabled(False)
        self.mesh_saveUV_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.mesh_saveUV_btn.setObjectName("mesh_saveUV_btn")
        self.horizontalLayout_7.addWidget(self.mesh_saveUV_btn)
        self.mesh_loadUV_btn = QtWidgets.QPushButton(self.saveSkin_frame_2)
        self.mesh_loadUV_btn.setEnabled(False)
        self.mesh_loadUV_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.mesh_loadUV_btn.setObjectName("mesh_loadUV_btn")
        self.horizontalLayout_7.addWidget(self.mesh_loadUV_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.saveSkin_frame_2)
        self.verticalLayout_3.addWidget(self.meshTool_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.sourceCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.source_frame.setVisible)
        QtCore.QObject.connect(self.meshToolsCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.meshTool_frame.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.lookat_label_2.setText(QtWidgets.QApplication.translate("Form", "SOURCES", None, -1))
        self.sources_refresh_btn.setText(QtWidgets.QApplication.translate("Form", "REFRESH", None, -1))
        self.sources_append_btn.setText(QtWidgets.QApplication.translate("Form", "APPEND", None, -1))
        self.sources_remove_btn.setText(QtWidgets.QApplication.translate("Form", "REMOVE", None, -1))
        self.sources_addToSource_btn.setText(QtWidgets.QApplication.translate("Form", "ADD SEL TO SOURCE", None, -1))
        self.connectSources_btn.setText(QtWidgets.QApplication.translate("Form", "CONNECT SOURCES", None, -1))
        self.lookat_label_3.setText(QtWidgets.QApplication.translate("Form", "MESH TOOLS", None, -1))
        self.mesh_transferUV_btn.setText(QtWidgets.QApplication.translate("Form", "TRANSFER UV", None, -1))
        self.mesh_cleaner_btn.setText(QtWidgets.QApplication.translate("Form", "CLEANER", None, -1))
        self.mesh_changeGeo_btn.setText(QtWidgets.QApplication.translate("Form", "CHANGE GEO", None, -1))
        self.mesh_browseUV_btn.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.mesh_saveUV_btn.setText(QtWidgets.QApplication.translate("Form", "SAVE UV MAP", None, -1))
        self.mesh_loadUV_btn.setText(QtWidgets.QApplication.translate("Form", "LOAD UV MAP", None, -1))

import icons_rc
