# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transformsWidget.ui'
#
# Created: Sat Jan 25 20:35:40 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(299, 641)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(240, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.spaceSwitchiesCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.spaceSwitchiesCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.spaceSwitchiesCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spaceSwitchiesCollapse_btn.setAutoFillBackground(True)
        self.spaceSwitchiesCollapse_btn.setStyleSheet("")
        self.spaceSwitchiesCollapse_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.spaceSwitchiesCollapse_btn.setIcon(icon)
        self.spaceSwitchiesCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.spaceSwitchiesCollapse_btn.setCheckable(True)
        self.spaceSwitchiesCollapse_btn.setChecked(True)
        self.spaceSwitchiesCollapse_btn.setDefault(False)
        self.spaceSwitchiesCollapse_btn.setFlat(True)
        self.spaceSwitchiesCollapse_btn.setObjectName("spaceSwitchiesCollapse_btn")
        self.horizontalLayout_17.addWidget(self.spaceSwitchiesCollapse_btn)
        self.lookat_label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label_4.sizePolicy().hasHeightForWidth())
        self.lookat_label_4.setSizePolicy(sizePolicy)
        self.lookat_label_4.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label_4.setFont(font)
        self.lookat_label_4.setObjectName("lookat_label_4")
        self.horizontalLayout_17.addWidget(self.lookat_label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.spaceSwitchies_frame = QtWidgets.QFrame(self.frame)
        self.spaceSwitchies_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.spaceSwitchies_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spaceSwitchies_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spaceSwitchies_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spaceSwitchies_frame.setObjectName("spaceSwitchies_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.spaceSwitchies_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.space_refresh_btn = QtWidgets.QPushButton(self.spaceSwitchies_frame)
        self.space_refresh_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.space_refresh_btn.setObjectName("space_refresh_btn")
        self.verticalLayout_3.addWidget(self.space_refresh_btn)
        self.space_createSpace_btn = QtWidgets.QPushButton(self.spaceSwitchies_frame)
        self.space_createSpace_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.space_createSpace_btn.setObjectName("space_createSpace_btn")
        self.verticalLayout_3.addWidget(self.space_createSpace_btn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spaceList_listWidget = QtWidgets.QListWidget(self.spaceSwitchies_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spaceList_listWidget.sizePolicy().hasHeightForWidth())
        self.spaceList_listWidget.setSizePolicy(sizePolicy)
        self.spaceList_listWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.spaceList_listWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.spaceList_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.spaceList_listWidget.setObjectName("spaceList_listWidget")
        self.horizontalLayout.addWidget(self.spaceList_listWidget)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.space_orient_btn = QtWidgets.QPushButton(self.spaceSwitchies_frame)
        self.space_orient_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.space_orient_btn.setObjectName("space_orient_btn")
        self.verticalLayout_6.addWidget(self.space_orient_btn)
        self.space_parent_btn = QtWidgets.QPushButton(self.spaceSwitchies_frame)
        self.space_parent_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.space_parent_btn.setObjectName("space_parent_btn")
        self.verticalLayout_6.addWidget(self.space_parent_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.spaceSwitchies_frame)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.controlToolsCollapse_btn = QtWidgets.QPushButton(self.frame)
        self.controlToolsCollapse_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.controlToolsCollapse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.controlToolsCollapse_btn.setAutoFillBackground(True)
        self.controlToolsCollapse_btn.setStyleSheet("")
        self.controlToolsCollapse_btn.setText("")
        self.controlToolsCollapse_btn.setIcon(icon)
        self.controlToolsCollapse_btn.setIconSize(QtCore.QSize(12, 12))
        self.controlToolsCollapse_btn.setCheckable(True)
        self.controlToolsCollapse_btn.setChecked(True)
        self.controlToolsCollapse_btn.setDefault(False)
        self.controlToolsCollapse_btn.setFlat(True)
        self.controlToolsCollapse_btn.setObjectName("controlToolsCollapse_btn")
        self.horizontalLayout_14.addWidget(self.controlToolsCollapse_btn)
        self.lookat_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_label.sizePolicy().hasHeightForWidth())
        self.lookat_label.setSizePolicy(sizePolicy)
        self.lookat_label.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lookat_label.setFont(font)
        self.lookat_label.setObjectName("lookat_label")
        self.horizontalLayout_14.addWidget(self.lookat_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.controlTool_frame = QtWidgets.QFrame(self.frame)
        self.controlTool_frame.setMinimumSize(QtCore.QSize(0, 300))
        self.controlTool_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlTool_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlTool_frame.setObjectName("controlTool_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.controlTool_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.transform_ZeroGrp_btn = QtWidgets.QToolButton(self.controlTool_frame)
        self.transform_ZeroGrp_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.transform_ZeroGrp_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.transform_ZeroGrp_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/skin/icon/transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transform_ZeroGrp_btn.setIcon(icon1)
        self.transform_ZeroGrp_btn.setIconSize(QtCore.QSize(50, 50))
        self.transform_ZeroGrp_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.transform_ZeroGrp_btn.setObjectName("transform_ZeroGrp_btn")
        self.gridLayout.addWidget(self.transform_ZeroGrp_btn, 0, 0, 1, 1)
        self.transform_InvMult_btn = QtWidgets.QToolButton(self.controlTool_frame)
        self.transform_InvMult_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.transform_InvMult_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.transform_InvMult_btn.setFont(font)
        self.transform_InvMult_btn.setIcon(icon1)
        self.transform_InvMult_btn.setIconSize(QtCore.QSize(40, 40))
        self.transform_InvMult_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.transform_InvMult_btn.setObjectName("transform_InvMult_btn")
        self.gridLayout.addWidget(self.transform_InvMult_btn, 0, 1, 1, 1)
        self.transform_meshHook_btn = QtWidgets.QToolButton(self.controlTool_frame)
        self.transform_meshHook_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.transform_meshHook_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.transform_meshHook_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/transform/icon/hookOnMesh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transform_meshHook_btn.setIcon(icon2)
        self.transform_meshHook_btn.setIconSize(QtCore.QSize(50, 50))
        self.transform_meshHook_btn.setShortcut("")
        self.transform_meshHook_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.transform_meshHook_btn.setObjectName("transform_meshHook_btn")
        self.gridLayout.addWidget(self.transform_meshHook_btn, 1, 0, 1, 1)
        self.transform_curveHook_btn = QtWidgets.QToolButton(self.controlTool_frame)
        self.transform_curveHook_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.transform_curveHook_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.transform_curveHook_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/transform/icon/hookOnCurve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transform_curveHook_btn.setIcon(icon3)
        self.transform_curveHook_btn.setIconSize(QtCore.QSize(50, 50))
        self.transform_curveHook_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.transform_curveHook_btn.setObjectName("transform_curveHook_btn")
        self.gridLayout.addWidget(self.transform_curveHook_btn, 1, 1, 1, 1)
        self.transform_matrixConn_btn = QtWidgets.QToolButton(self.controlTool_frame)
        self.transform_matrixConn_btn.setEnabled(False)
        self.transform_matrixConn_btn.setMinimumSize(QtCore.QSize(75, 75))
        self.transform_matrixConn_btn.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.transform_matrixConn_btn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/skin/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transform_matrixConn_btn.setIcon(icon4)
        self.transform_matrixConn_btn.setIconSize(QtCore.QSize(40, 40))
        self.transform_matrixConn_btn.setShortcut("")
        self.transform_matrixConn_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.transform_matrixConn_btn.setObjectName("transform_matrixConn_btn")
        self.gridLayout.addWidget(self.transform_matrixConn_btn, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.controlTool_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.controlToolsCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.controlTool_frame.setVisible)
        QtCore.QObject.connect(self.spaceSwitchiesCollapse_btn, QtCore.SIGNAL("clicked(bool)"), self.spaceSwitchies_frame.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.lookat_label_4.setText(QtWidgets.QApplication.translate("Form", "SPACE SWITCHES", None, -1))
        self.space_refresh_btn.setText(QtWidgets.QApplication.translate("Form", "REFRESH", None, -1))
        self.space_createSpace_btn.setText(QtWidgets.QApplication.translate("Form", "CREATE SPACE", None, -1))
        self.space_orient_btn.setText(QtWidgets.QApplication.translate("Form", "ORIENT", None, -1))
        self.space_parent_btn.setText(QtWidgets.QApplication.translate("Form", "PARENT", None, -1))
        self.lookat_label.setText(QtWidgets.QApplication.translate("Form", "CONTROL TOOLS", None, -1))
        self.transform_ZeroGrp_btn.setText(QtWidgets.QApplication.translate("Form", "ZERO GRP", None, -1))
        self.transform_InvMult_btn.setText(QtWidgets.QApplication.translate("Form", "INV MULT", None, -1))
        self.transform_meshHook_btn.setText(QtWidgets.QApplication.translate("Form", "MESH HOOK", None, -1))
        self.transform_curveHook_btn.setText(QtWidgets.QApplication.translate("Form", "CURVE HOOK", None, -1))
        self.transform_matrixConn_btn.setText(QtWidgets.QApplication.translate("Form", "MATRIX CONN", None, -1))

import icons_rc
